### ISSUE TITLE
How to close HEC RAS messages

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#212]
![image](https://github.com/user-attachments/assets/0e0a4fa2-cfef-4935-bbdf-3c96c90d4d2d)

**Comment by sclaw** [comment]
I have tested this model
collection_id: mip_17090003
model_name: uw_group22
submodel_name: 23763573
The new feature to dismiss running jobs is able to close this window and quit the corresponding RAS process.  For this reason, we consider this issue resolved.

That said, this behavior is non-optimal because the model run will display as revoked in the huey task logs.  Users should be warned that they will need to revoke the task and that the run may have succeeded despite being revoked.  Alternatively, Ripple1d should adjust the sub model ahead of execution.  For this reason, I have opened #249.
