### ISSUE TITLE
Make sure execution times do not exponentially increase when running jobs in parallel

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#236]

**Comment by sclaw** [comment]
![ripple1d_throughput](https://github.com/user-attachments/assets/d4d3f820-bd64-4d84-95fb-cb5d57212080)

We ran ~800 models from the ble_12020001_UpperNeches collection on a VM with 96 vcpus and 200GB of RAM under a variety of thread conditions.  The results are shown above.  Execution time increases as the number of jobs running in parallel does, but it appears to be a linear increase rather than exponential.  The increased execution time is offset by concurrency such that total ripple1d throughput increases with thread number.  At around 30 threads, ripple1d throughput appears to flatline, and it is unclear if that limit would be consistent across machines with different hardware.
